# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gossy < Formula
  desc "Gossy: A versatile AWS CLI tool for efficient management across AWS services."
  homepage "https://github.com/mangchhe/homebrew-gossy"
  version "0.0.1"

  on_macos do
    on_intel do
      url "https://github.com/mangchhe/gossy/releases/download/v0.0.1/gossy_Darwin_x86_64.tar.gz"
      sha256 "a4c4443684e1547643b94713fc1f0007367a8744c37b0b295565dcadb160f63a"

      def install
        bin.install "gossy"
      end
    end
    on_arm do
      url "https://github.com/mangchhe/gossy/releases/download/v0.0.1/gossy_Darwin_arm64.tar.gz"
      sha256 "1027ddf568ec349e708d886c7bbfcdbc8c619679234407da66fa683c0f401f69"

      def install
        bin.install "gossy"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/mangchhe/gossy/releases/download/v0.0.1/gossy_Linux_x86_64.tar.gz"
        sha256 "150f55cfce018455f70c08206500698354522d5ad56c981085b9f01844c9829d"

        def install
          bin.install "gossy"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/mangchhe/gossy/releases/download/v0.0.1/gossy_Linux_arm64.tar.gz"
        sha256 "f75745bb890bfdee703f2d6a80a0b8b2715c1151faa0659d70f30829c9f3cce6"

        def install
          bin.install "gossy"
        end
      end
    end
  end
end
